/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "stm32f0xx.h"

int main(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER5_0;

	while(1){
		uint32_t vector=0b10101001110111011100101010000000;

		for (uint8_t i=0; i<32; i++){
			if (vector & (1<<(31-i))) {
				GPIOA->BSRR = (1<<5);
			}
			else{
				GPIOA->BRR = (1<<5);
			}
			//vector <<=i;
			for (volatile uint32_t i = 0; i < 100000; i++) {}
		}
	}
}
